# Generated by Django 5.2.1 on 2025-05-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reservation_hour_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='halisaha',
            name='opening_hours',
            field=models.CharField(default='09:00 - 23:00', help_text='Örn: 09:00 - 23:00', max_length=100),
        ),
    ]
