# Generated by Django 5.2.1 on 2025-05-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_halisaha_opening_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_sahalar',
            field=models.ManyToManyField(blank=True, related_name='favori_kullanicilar', to='main.halisaha'),
        ),
    ]
